apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: webapp-1-staging-green
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io/background 
  labels:
    ENV: staging
spec:
  project: green
  source:
    repoURL: 'https://github.com/tmather99/argocd.git'
    path: k8s/staging/clusters/green/apps/webapp-1
    targetRevision: main
  destination:
    name: 'cloudgate@tmather@jedi-staging-green.ap-northeast-1.eksctl.io'
    namespace: default
  syncPolicy:
    syncOptions:
    - CreatNamespace=true
    automated:
      selfHeal: true
