apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: otel-collector-staging-argocd
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io  
  labels:
    ENV: staging
spec:
  project: argocd
  source:
    repoURL: 'https://github.com/tmather99/argocd.git'
    path: k8s/staging/observability/otel-collector
    targetRevision: main
  destination:
    name: 'cloudgate@tmather@jedi-staging-argocd.ap-northeast-1.eksctl.io'
    namespace: default
  syncPolicy:
    syncOptions:
    - CreatNamespace=true
    automated:
      selfHeal: true
