appId: gru
port: 80
memory: "2048Mi"
cpu: "1024m"  
replicas: 1
configmap:
  name: gru-configmap-v1
image:
  name: projects.registry.vmware.com/jedi/gru
  tag: v240128_001

OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector-service.observability.svc.cluster.local:4317"
OTEL_EXPORTER_OTLP_PROTOCOL: "grpc"
OTEL_EXPORTER_OTLP_HEADERS:
