apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dapr-staging-iris
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io  
  labels:
    ENV: staging
spec:
  project: iris
  source:
    repoURL: 'https://dapr.github.io/helm-charts/'
    targetRevision: 1.12.4
    chart: dapr
  destination:
    name: 'cloudgate@tmather@jedi-staging-iris.ap-northeast-1.eksctl.io'
    namespace: dapr-system
  ignoreDifferences:
    - kind: Secret
      name: dapr-trust-bundle
      namespace: dapr-system
      jsonPointers:
        - /metadata/labels
        - /data
    - group: admissionregistration.k8s.io
      kind: MutatingWebhookConfiguration
      name: dapr-sidecar-injector
      jsonPointers:
        - /webhooks/0/clientConfig/caBundle  
  syncPolicy:
    syncOptions:  
    - CreatNamespace=true
    - RespectIgnoreDifferences=true
    automated:
      selfHeal: true
