apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: seq-staging-iris
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io/background 
  labels:
    ENV: staging
spec:
  project: iris
  source:
    repoURL: 'https://github.com/tmather99/argocd.git'
    path: k8s/staging/utils/seq
    targetRevision: main
    directory:
      recurse: true    
  destination:
    name: 'cloudgate@tmather@jedi-staging-iris.ap-northeast-1.eksctl.io'
    namespace: default
  syncPolicy:
    syncOptions:
    - CreatNamespace=true
    automated:
      selfHeal: true
