apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: gru-tls
  namespace: default
spec:
  secretName: gru-tls
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  dnsNames:
  - gru-staging-green.assistdevtest.com
