apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: otel-demo-tls
  namespace: default
spec:
  secretName: otel-demo-tls
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  dnsNames:
  - otel-demo-staging-green.assistdevtest.com
