extraScrapeConfigs: |
  - job_name: aggregated-trace-metrics
    static_configs:
      - targets:
          - otel-collector-service.observability.svc.cluster.local:8889

  - job_name: services
    static_configs:
      - targets:
          - gru-service.default.svc.cluster.local:80
          - macminion-service.default.svc.cluster.local:80
          - anchorservice-service.default.svc.cluster.local:80
          - enrollmentservice-service.default.svc.cluster.local:80
          - cadvisor.observability.svc.cluster.local:8080
          - kube-state-metrics.observability.svc.cluster.local:8080
