apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: perfdevice-assistdevtest-tls
  namespace: default
spec:
  secretName: perfdevice-assistdevtest-tls
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  dnsNames:
  - perfdevice-staging-orange.assistdevtest.com
