apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: idp-assistdevtest-tls
  namespace: default
spec:
  secretName: idp-assistdevtest-tls
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  dnsNames:
  - idp.assistdevtest.com
