apiVersion: apps/v1
kind: Deployment
metadata:
  name: macminion-app
spec:
  selector:
    matchLabels:
      app: macminion-app
  replicas: 1
  template:
    metadata:
      labels:
        app: macminion-app
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "macminion"
        dapr.io/app-port: "8080"
        dapr.io/app-ssl: "false"
        dapr.io/config: "tracing"
        dapr.io/enable-metrics: "true"
        dapr.io/metrics-port: "9090" 
    spec:      
      volumes:
      - name: pfx-volume
        secret:
          secretName: assistdevtest-com-pfx
      containers:
      - name: macminion
        image: projects.registry.vmware.com/jedi/macminion:v231225_0002
        volumeMounts:
        - name: pfx-volume
          mountPath: /https
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: "128Mi"
            cpu: "200m"  
        imagePullPolicy: Always
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Development"        
        - name: ASPNETCORE_URLS
          value: "http://+:8080"        
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: http://otel-collector-service.observability.svc.cluster.local:4317
        - name: OTEL_EXPORTER_OTLP_PROTOCOL
          value: grpc
        - name: SEQ_SERVER_URL
          value: http://seq-service.default.svc.cluster.local        
        - name: ASPNETCORE_Kestrel__Certificates__Default__Path
          value: "/https/assistdevtest-com.pfx"        
        - name: ASPNETCORE_Kestrel__Certificates__Default__Password
          valueFrom:
            secretKeyRef:
              name: pfx-passwords
              key: assistdevtest-com-pfx-password
        - name: IdpServerUri
          value: "https://idp.assistdevtest.com"
        - name: ConnectionStrings__GlobomanticsDb
          value: "Server=sql.assistdevtest.com;Database=Globomantics;User Id=sa;Password=AssistJedi2023;MultipleActiveResultSets=true;TrustServerCertificate=True"
---
apiVersion: v1
kind: Service
metadata:
  name: macminion-service
spec:
  selector:
    app: macminion-app  
  ports:
    - protocol: TCP 
      port: 80
      targetPort: 8080
  type: ClusterIP
