apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: anchorservice-staging-yellow
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io/background 
  labels:
    ENV: staging
spec:
  project: yellow
  source:
    repoURL: 'https://github.com/tmather99/argocd.git'
    path: k8s/staging/apps/anchorservice
    targetRevision: main
  destination:
    name: 'cloudgate@tmather@jedi-staging-yellow.ap-northeast-1.eksctl.io'
    namespace: default
  syncPolicy:
    syncOptions:
    - CreatNamespace=true
    automated:
      selfHeal: true
