appId: authminion
port: 443
memory: "2048Mi"
cpu: "1024m"  
replicas: 1
idpUrl: "https://authminion-staging-red.assistdevtest.com"
configmap:
  name: authminion-configmap-v1
image:
  name: projects.registry.vmware.com/jedi/authminion
  tag: v240222_001

OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector-service.observability.svc.cluster.local:4317"
OTEL_EXPORTER_OTLP_PROTOCOL: "grpc"
OTEL_EXPORTER_OTLP_HEADERS:
