apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-state-metrics-staging-purple
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io  
  labels:
    ENV: staging
spec:
  project: purple
  source:
    repoURL: 'https://charts.bitnami.com/bitnami'
    targetRevision: 3.10.1
    chart: kube-state-metrics
    helm:
      releaseName: kube-state-metrics
      values: |-
        replicas: 1
  destination:
    name: 'cloudgate@tmather@jedi-staging-purple.ap-northeast-1.eksctl.io'
    namespace: observability
  syncPolicy:
    syncOptions:
    - CreatNamespace=true
    automated:
      selfHeal: true
