{
 "title": "Latency & Traffic & Errors",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "ingress",
    "query": {
     "query": "label_values(nginx_ingress_controller_request_duration_seconds_bucket, ingress)"
    }
   },
   {
    "name": "status",
    "query": "success : [2-3].*,error : [4-5].*"
   },
   { "name": "method", "query": "GET,POST,PUT,DELETE" }
  ]
 },
 "panels": [
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 14, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(\n    0.99, sum(\n        rate(\n            nginx_ingress_controller_request_duration_seconds_bucket\n            {\n                ingress=~\"$ingress\",\n                status=~\"$status\",\n                method=~\"$method\"\n            }[1m])) by (le, ingress)\n    )",
     "legendFormat": "P99"
    },
    {
     "expr": "histogram_quantile(\n    0.90, sum(\n        rate(\n            nginx_ingress_controller_request_duration_seconds_bucket\n            {\n                ingress=~\"$ingress\",\n                status=~\"$status\",\n                method=~\"$method\"\n            }[1m])) by (le, ingress)\n    )",
     "legendFormat": "P90"
    },
    {
     "expr": "histogram_quantile(\n    0.50, sum(\n        rate(\n            nginx_ingress_controller_request_duration_seconds_bucket\n            {\n                ingress=~\"$ingress\",\n                status=~\"$status\",\n                method=~\"$method\"\n            }[1m])) by (le, ingress)\n    )",
     "legendFormat": "P50"
    }
   ]
  },
  {
   "title": "Traffic",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 10, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "round(\n    sum(\n        irate(\n            nginx_ingress_controller_requests\n            {\n                ingress=~\"$ingress\"\n            }[1m]\n            )\n        ) by (ingress), 0.001)",
     "legendFormat": "Traffic"
    }
   ]
  },
  {
   "title": "Availability (non-4|5xx responses)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(\n    rate(\n        nginx_ingress_controller_requests\n        {\n            ingress=~\"$ingress\",\n            status!~\"[4-5].*\"\n        }[1m])) by (ingress) /\nsum(\n    rate(\n        nginx_ingress_controller_requests\n        {\n            ingress=~\"$ingress\"\n        }[1m])) by (ingress)",
     "legendFormat": "{{ ingress }}"
    }
   ]
  }
 ]
}