apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: observability-tls
  namespace: observability
spec:
  secretName: observability-tls
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  dnsNames:
  - grafana-staging-yellow.assistdevtest.com
  - prometheus-staging-yellow.assistdevtest.com
  - cadvisor-staging-yellow.assistdevtest.com
  - kube-state-metrics-staging-yellow.assistdevtest.com
