apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: statestore
spec:
  type: state.redis
  version: v1
  metadata:
  - name: keyPrefix
    value: none
  - name: redisHost
    value: jedi-staging-iris-redis.nsg6a7.ng.0001.apne1.cache.amazonaws.com:6379
