apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appId }}-app
spec:
  selector:
    matchLabels:
      app: {{ .Values.appId }}-app
  replicas: {{ .Values.replicas }}
  template:
    metadata:
      labels:
        app: {{ .Values.appId }}-app
      annotations:
        dapr.io/enabled: "false"
        dapr.io/app-id: "{{ .Values.appId }}"
        dapr.io/app-port: "8080"
        dapr.io/app-ssl: "false"
        dapr.io/config: "tracing"
        dapr.io/enable-metrics: "false"
        dapr.io/metrics-port: "9090" 
        sidecar.opentelemetry.io/inject: "false"
    spec:      
      volumes:
      - name: pfx-volume
        secret:
          secretName: assistdevtest-com-pfx
      containers:
      - name: {{ .Values.appId }}
        image: {{ .Values.image.name }}:{{ .Values.image.tag }}
        imagePullPolicy: Always
        volumeMounts:
        - name: pfx-volume
          mountPath: /https
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: {{ .Values.memory }}
            cpu: {{ .Values.cpu }}
        env:
        - name: IDP_URL
          value:  {{ .Values.idpUrl }}
        - name: ASPNETCORE_ENVIRONMENT
        - name: Clients__GruUrl
          value: {{ .Values.GruUrl }}
          value: "Development"        
        - name: ASPNETCORE_URLS
          value: "http://+:8080"        
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: {{ .Values.OTEL_EXPORTER_OTLP_ENDPOINT }}
        - name: OTEL_EXPORTER_OTLP_PROTOCOL
          value: {{ .Values.OTEL_EXPORTER_OTLP_PROTOCOL }}
        - name: OTEL_EXPORTER_OTLP_HEADERS
          value: {{ .Values.OTEL_EXPORTER_OTLP_HEADERS }}
        - name: ASPNETCORE_Kestrel__Certificates__Default__Path
          value: "/https/assistdevtest-com.pfx"        
        - name: ASPNETCORE_Kestrel__Certificates__Default__Password
          valueFrom:
            secretKeyRef:
              name: pfx-passwords
              key: assistdevtest-com-pfx-password
        - name: IdpServerUri
          value: "https://idp.assistdevtest.com"
        - name: ConnectionStrings__GlobomanticsDb
          value: "Server=sql.assistdevtest.com;Database=Globomantics;User Id=sa;Password=AssistJedi2023;MultipleActiveResultSets=true;TrustServerCertificate=True"
