appId: perfdevice
port: 80
memory: "512Mi"
cpu: "512m"  
replicas: 3
# anchorUrl: https://perfdevice-staging-purple.assistdevtest.com
anchorUrl: http://anchorservice-service
configmap:
  name: perfdevice-configmap-v1
image:
  name: projects.registry.vmware.com/jedi/perfdevice
  tag: v231201_0002

OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector-service.observability.svc.cluster.local:4317"
OTEL_EXPORTER_OTLP_PROTOCOL: "grpc"
OTEL_EXPORTER_OTLP_HEADERS:
