apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gru-staging-classic
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io  
  labels:
    ENV: staging
spec:
  project: classic
  source:
    repoURL: 'https://github.com/tmather99/argocd.git'
    path: k8s/staging/clusters/classic/apps/testbed/gru
    targetRevision: main
  destination:
    name: 'cloudgate@tmather@jedi-staging-classic.ap-northeast-1.eksctl.io'
    namespace: default
  syncPolicy:
    syncOptions:
    - CreatNamespace=true
    automated:
      selfHeal: true
