apiVersion: apps/v1
kind: Deployment
metadata:
  name: imagegallery-client-app
spec:
  selector:
    matchLabels:
      app: imagegallery-client-app
  replicas: 1
  template:
    metadata:
      labels:
        app: imagegallery-client-app
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "imagegallery-client"
        dapr.io/app-port: "443"
        dapr.io/app-ssl: "true"
        dapr.io/config: "tracing"
        dapr.io/enable-metrics: "true"
        dapr.io/metrics-port: "9090"        
    spec:      
      volumes:
      - name: pfx-volume
        secret:
          secretName: assistdevtest-com-pfx
      containers:
      - name: imagegallery-client
        image: tmather99/imagegallery-client:v9
        volumeMounts:
        - name: pfx-volume
          mountPath: /https
        ports:
        - containerPort: 443
        resources:
          limits:
            memory: "128Mi"
            cpu: "200m"  
        imagePullPolicy: Always
        env:
        - name: SEQ_SERVER_URL
          value: "http://seq-service"        
        - name: ASPNETCORE_URLS
          value: "https://+:443"        
        - name: ASPNETCORE_Kestrel__Certificates__Default__Path
          value: "/https/assistdevtest-com.pfx"        
        - name: ASPNETCORE_Kestrel__Certificates__Default__Password
          valueFrom:
            secretKeyRef:
              name: pfx-passwords
              key: assistdevtest-com-pfx-password
        - name: ImageGalleryAPIRoot
          value: "https://api.assistdevtest.com/"
        - name: IdpServerUri
          value: "https://idp.assistdevtest.com/"
---
apiVersion: v1
kind: Service
metadata:
  name: imagegallery-client-service
spec:
  selector:
    app: imagegallery-client-app  
  ports:
    - protocol: TCP 
      port: 443
      targetPort: 443
  type: ClusterIP
