appId: anchorservice
port: 80
memory: "2048Mi"
cpu: "1024m"  
replicas: 3
configmap:
  name: anchorservice-configmap-v1
image:
  name: projects.registry.vmware.com/jedi/anchorservice
  tag: v231201_0002

OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector-service.observability.svc.cluster.local:4317"
OTEL_EXPORTER_OTLP_PROTOCOL: "grpc"
OTEL_EXPORTER_OTLP_HEADERS:

# OTEL_EXPORTER_OTLP_ENDPOINT: "https://otlp-gateway-prod-us-west-0.grafana.net/otlp"
# OTEL_EXPORTER_OTLP_PROTOCOL: "http/protobuf"
# OTEL_EXPORTER_OTLP_HEADERS: "Authorization=Basic ODQ3NDk4OmdsY19leUp2SWpvaU1UQTBORGMyTkNJc0ltNGlPaUp6ZEdGamF5MDRORGMwT1RndGIzUnNjQzEzY21sMFpTMXZkR1ZzSWl3aWF5STZJbE5ET1RVell6TTFTMjkwTm5sb1J6aFBjWEkwU0RaQk9TSXNJbTBpT25zaWNpSTZJbkJ5YjJRdGRYTXRkMlZ6ZEMwd0luMTk="