appId: enrollmentservice
port: 80
memory: "2048Mi"
cpu: "1024m"  
replicas: 3
configmap:
  name: enrollmentservice-configmap-v1
image:
  name: projects.registry.vmware.com/jedi/enrollmentservice
  tag: v231201_0002

OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector-service.observability.svc.cluster.local:4317"
OTEL_EXPORTER_OTLP_PROTOCOL: "grpc"
OTEL_EXPORTER_OTLP_HEADERS:
