apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-staging-blue
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io  
  labels:
    ENV: staging
spec:
  project: blue
  source:
    repoURL: 'https://prometheus-community.github.io/helm-charts'
    targetRevision: 25.8.0
    chart: prometheus
    helm:
      releaseName: dapr-prom
      values: |-
        extraScrapeConfigs: |
          - job_name: aggregated-trace-metrics
            static_configs:
              - targets:
                  - otel-collector-service.observability.svc.cluster.local:8889
          - job_name: services
            static_configs:
              - targets:
                  - gru-service.default.svc.cluster.local:80
                  - macminion-service.default.svc.cluster.local:80
                  - anchorservice-service.default.svc.cluster.local:80
                  - enrollmentservice-service.default.svc.cluster.local:80
                  - cadvisor.observability.svc.cluster.local:8080
                  - kube-state-metrics.observability.svc.cluster.local:8080                 
  destination:
    name: 'cloudgate@tmather@jedi-staging-blue.ap-northeast-1.eksctl.io'
    namespace: observability
  syncPolicy:
    syncOptions:
    - CreatNamespace=true
    automated:
      selfHeal: true
