apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: macminion-staging-testbed
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io  
  labels:
    ENV: staging
spec:
  project: testbed
  source:
    repoURL: 'https://github.com/tmather99/argocd.git'
    path: k8s/staging/clusters/testbed/apps/macminion
    targetRevision: main
  destination:
    name: 'cloudgate@tmather@jedi-staging-testbed.ap-northeast-1.eksctl.io'
    namespace: default
  syncPolicy:
    syncOptions:
    - CreatNamespace=true
    automated:
      selfHeal: true
