apiVersion: v1
kind: Service
metadata:
  name: seq-service
spec:
  selector:
    app: seq-app  
  type: ClusterIP  
  ports:
    - protocol: TCP 
      port: 80
      targetPort: 80  
---
apiVersion: v1
kind: Service
metadata:
  name: seq-classic-service
spec:
  selector:
    app: seq-app  
  type: LoadBalancer  
  ports:
    - name: seq-endpoint
      port: 5341
      protocol: TCP
      targetPort: 5341
