apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: macminion-tls
  namespace: default
spec:
  secretName: macminion-tls
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  dnsNames:
  - macminion-staging-blue.assistdevtest.com
