apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-config
  namespace: observability
data:
  otel-collector-config: |-

    extensions:
      basicauth/otlp:
        client_auth:
          username: 847498
          password: glc_eyJvIjoiMTA0NDc2NCIsIm4iOiJzdGFjay04NDc0OTgtb3RscC13cml0ZS1vbHRwIiwiayI6IlZhTEZMWTJQbDdlMEN0NUdUaDU0MTY5MiIsIm0iOnsiciI6InByb2QtdXMtd2VzdC0wIn19
      basicauth/metrics:
        client_auth:
          username: 1405825
          password: glc_eyJvIjoiMTA0NDc2NCIsIm4iOiJzdGFjay04NDc0OTgtaG0tcmVhZC1qZWRpLXN0YWdpbmctdGVzdGJlZC1wcm9tZXRoZXVzIiwiayI6IkJ1RlFGM0E2RjVheEZhSzgxMUo4OTQ2byIsIm0iOnsiciI6InByb2QtdXMtd2VzdC0wIn19

    exporters:     
      otlphttp:
        auth:
          authenticator: basicauth/otlp
        endpoint: https://otlp-gateway-prod-us-west-0.grafana.net/otlp

      prometheusremotewrite:
        auth:
          authenticator: basicauth/metrics
        endpoint: https://prometheus-prod-36-prod-us-west-0.grafana.net/api/prom/push

      prometheus:
        endpoint: ":8889"
      otlp:
        endpoint: tempo.observability.svc.cluster.local:4317
        tls:
          insecure: true    
      loki:
        endpoint: http://loki.observability:3100/loki/api/v1/push
        tls:
          insecure: true

    receivers:
      otlp:
        protocols:
          grpc:
          http:

      prometheus:
        config:
          scrape_configs:

          - job_name: 'otel-collector'
            scrape_interval: 10s
            static_configs:
            - targets: ['0.0.0.0:8888']

          - job_name: aggregated-trace-metrics
            scrape_interval: 10s
            static_configs:
              - targets: ['otel-collector-service.observability.svc.cluster.local:8889']

          - job_name: 'gru'
            scrape_interval: 10s
            static_configs:
            - targets: ['gru-service.default.svc.cluster.local']

          - job_name: 'macminion'
            scrape_interval: 10s
            static_configs:
            - targets: ['macminion-service.default.svc.cluster.local']

          - job_name: 'authminion'
            scrape_interval: 10s
            static_configs:
            - targets: ['authminion-service.default.svc.cluster.local']

          - job_name: 'anchorservice'
            scrape_interval: 10s
            static_configs:
            - targets: ['anchorservice-service.default.svc.cluster.local',
                        'anchorservice-service.default.svc.cluster.local:9464'
                       ]

          - job_name: 'enrollmentservice'
            scrape_interval: 10s
            static_configs:
            - targets: ['enrollmentservice-service.default.svc.cluster.local',
                        'enrollmentservice-service.default.svc.cluster.local:9464'
                       ]

    processors:
      batch:
        timeout: 15s
        send_batch_size: 10
    
    service:
      extensions: [basicauth/otlp, basicauth/metrics]
      pipelines:
        metrics:
          receivers: [otlp, prometheus]
          processors: [batch]
          exporters: [prometheus, prometheusremotewrite, otlphttp]
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [otlp, otlphttp] 
        logs:
          receivers: [otlp]
          processors: [batch]
          exporters: [loki, otlphttp] 
