apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-config
  namespace: observability
data:
  otel-collector-config: |-
    receivers:
      otlp:
        protocols:
          grpc:
          http:
    processors:
      batch:
        timeout: 15s
        send_batch_size: 10
    exporters:
      prometheus:
        endpoint: ":8889"
      otlp:
        endpoint: tempo.observability.svc.cluster.local:4317
        tls:
          insecure: true    
      loki:
        endpoint: http://loki.observability:3100/loki/api/v1/push
        tls:
          insecure: true
    service:
      pipelines:
        metrics:
          receivers: [otlp]
          exporters: [prometheus]
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [otlp] 
        logs:
          receivers: [otlp]
          processors: [batch]
          exporters: [loki] 
