apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: tracing
spec:
  tracing:
    samplingRate: "1"
    otel:
      endpointAddress: "otel-collector.observability.svc.cluster.local:4317"
      protocol: grpc
      isSecure: false
  metric:
    enabled: true      