appId: perfclient
memory: "32Mi"
cpu: "100m"  
replicas: 5
image:
  name: curlimages/curl
  tag: latest

OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector-service.observability.svc.cluster.local:4317"
OTEL_EXPORTER_OTLP_PROTOCOL: "grpc"
OTEL_EXPORTER_OTLP_HEADERS:
