appId: perfclient
memory: "32Mi"
cpu: "100m"  
replicas: 5
image:
  name: curlimages/curl
  tag: latest

OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector-service.observability.svc.cluster.local:4317"
OTEL_EXPORTER_OTLP_PROTOCOL: "grpc"
OTEL_EXPORTER_OTLP_HEADERS:

# OTEL_EXPORTER_OTLP_ENDPOINT: "https://otlp-gateway-prod-us-west-0.grafana.net/otlp"
# OTEL_EXPORTER_OTLP_PROTOCOL: "http/protobuf"
# OTEL_EXPORTER_OTLP_HEADERS: "Authorization=Basic ODQ3NDk4OmdsY19leUp2SWpvaU1UQTBORGMyTkNJc0ltNGlPaUp6ZEdGamF5MDRORGMwT1RndGIzUnNjQzEzY21sMFpTMXZkR1ZzSWl3aWF5STZJbE5ET1RVell6TTFTMjkwTm5sb1J6aFBjWEkwU0RaQk9TSXNJbTBpT25zaWNpSTZJbkJ5YjJRdGRYTXRkMlZ6ZEMwd0luMTk="