default:
  envOverrides:
  - name: 'OTEL_COLLECTOR_NAME'
    value: $(OTEL_K8S_NODE_NAME)
opentelemetry-collector:
  mode: daemonset
  presets:
    logsCollection:
      enabled: true
      includeCollectorLogs: false
  config:
    extensions:
      basicauth/traces:
        username: "799597"
        password: "glc_eyJvIjoiMTA0NDc2NCIsIm4iOiJzdGFjay04NDc0OTgtaW50ZWdyYXRpb24tb2x0cC1hY2Nlc3MtcG9saWN5LXRva2VuIiwiayI6IkZFYTYzQmVlODEwUWl2ODhwejU2czBVYiIsIm0iOnsiciI6InByb2QtdXMtd2VzdC0wIn19"
      basicauth/metrics:
        client_auth:
			    username: "1405825"
			    password: "glc_eyJvIjoiMTA0NDc2NCIsIm4iOiJzdGFjay04NDc0OTgtaW50ZWdyYXRpb24tb2x0cC1hY2Nlc3MtcG9saWN5LXRva2VuIiwiayI6IkZFYTYzQmVlODEwUWl2ODhwejU2czBVYiIsIm0iOnsiciI6InByb2QtdXMtd2VzdC0wIn19"      
      basicauth/logs:
        client_auth:
          username: "801904"
          password: "glc_eyJvIjoiMTA0NDc2NCIsIm4iOiJzdGFjay04NDc0OTgtaW50ZWdyYXRpb24tb2x0cC1hY2Nlc3MtcG9saWN5LXRva2VuIiwiayI6IkZFYTYzQmVlODEwUWl2ODhwejU2czBVYiIsIm0iOnsiciI6InByb2QtdXMtd2VzdC0wIn19"        
    exporters:
      otlp:
        endpoint: https://tempo-prod-15-prod-us-west-0.grafana.net/tempo
        tls:
          insecure: false
        auth:
          authenticator: basicauth/traces

      prometheusremotewrite:
        endpoint: https://prometheus-prod-36-prod-us-west-0.grafana.net/api/prom/push
        auth:
          authenticator: basicauth/metrics

      loki:
        endpoint: https://logs-prod-021.grafana.net/loki/api/v1/push
        auth:
          authenticator: basicauth/logs

    processors:
      spanmetrics:
        metrics_exporter: prometheusremotewrite

    service:
      extensions: [ basicauth/traces, basicauth/metrics, basicauth/logs, health_check , memory_ballast ]
      pipelines:
        metrics:
          exporters: [prometheusremotewrite]
        logs:
          receivers: [filelog]
          exporters: [loki]