apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: webclient-staging-asterix
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io  
  labels:
    ENV: staging
spec:
  project: asterix
  source:
    repoURL: 'https://github.com/tmather99/argocd.git'
    path: k8s/staging/clusters/asterix/apps/webclient
    targetRevision: main
  destination:
    name: 'cloudgate@tmather@jedi-staging-asterix.ap-northeast-1.eksctl.io'
    namespace: default
  syncPolicy:
    syncOptions:
    - CreatNamespace=true
    automated:
      selfHeal: true
