apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis-commander-staging-red
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io  
  labels:
    ENV: staging
spec:
  project: red
  source:
    repoURL: 'ssh://git@stash.air-watch.com:7999/aplnt/argocd.git'
    path: k8s/staging/clusters/red/redis-commander
    targetRevision: main
    directory:
      recurse: true    
  destination:
    name: 'cloudgate@tmather@jedi-staging-red.ap-northeast-1.eksctl.io'
    namespace: default
  syncPolicy:
    syncOptions:
    - CreatNamespace=true
    automated:
      selfHeal: true
