apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: webapp-1-staging-blue
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io  
  labels:
    ENV: staging
spec:
  project: blue
  source:
    repoURL: 'https://github.com/tmather99/argocd.git'
    path: k8s/staging/apps/testbed/staging/blue/webapp-1
    targetRevision: main
  destination:
    name: 'cloudgate@tmather@jedi-staging-blue.ap-northeast-1.eksctl.io'
    namespace: default
  syncPolicy:
    syncOptions:
    - CreatNamespace=true
    automated:
      selfHeal: true
