apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: jedi-staging-iris
  region: ap-northeast-1
  version: "1.29"
 
vpc:
  id: vpc-024ffa78034e61c48
  subnets:
    private:
      ap-northeast-1a:
        id: subnet-04cb8b613f200ae0a
      ap-northeast-1c:
        id: subnet-07a45b7a519d58bcd
    public:
      ap-northeast-1a:
        id: subnet-01bdd2c6abbf8262a
      ap-northeast-1c:
        id: subnet-06c5e0ebbf8bd3205

iam:
  withOIDC: true
 
addons:
- name: aws-ebs-csi-driver
  version: v1.26.1-eksbuild.1
  attachPolicyARNs:
  - arn:aws:iam::aws:policy/service-role/AmazonEBSCSIDriverPolicy
 
managedNodeGroups:
  - name: managed-ng-jedi-staging-iris
    instanceType: m7a.xlarge
    privateNetworking: true
    minSize: 3
    maxSize: 3
    desiredCapacity: 3
    volumeSize: 20
    ssh:
      allow: true