apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: api-assistdevtest-tls
  namespace: default
spec:
  secretName: api-assistdevtest-tls
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  dnsNames:
  - api.assistdevtest.com
