apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: authminion-tls
  namespace: default
spec:
  secretName: authminion-tls
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  dnsNames:
  - authminion-staging-argocd.assistdevtest.com
