apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: otel-collector-tls
  namespace: observability
spec:
  secretName: otel-collector-tls
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  dnsNames:
  - otel-collector-staging-argocd.assistdevtest.com
