appId: webapp-1
port: 80
memory: "2048Mi"
cpu: "1024m"  
replicas: 1
idpUrl: "https://authminion-staging-testbed.assistdevtest.com"
configmap:
  name: webapp-1-configmap-v1
image:
  name: projects.registry.vmware.com/jedi/webapp-1
  tag: v240215_005

OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector-service.observability.svc.cluster.local:4317"
OTEL_EXPORTER_OTLP_PROTOCOL: "grpc"
OTEL_EXPORTER_OTLP_HEADERS:
