apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appId }}-service
spec:
  selector:
    app: {{ .Values.appId }}-app 
  type: ClusterIP
  ports:
    - name: idp-https
      protocol: TCP      
      port: {{ .Values.port }}
      targetPort: 5001
