apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appId }}-service
spec:
  selector:
    app: {{ .Values.appId }}-app 
  ports:
    - name: idp
      protocol: TCP      
      port: {{ .Values.port }}
      targetPort: 5001
    - name: http
      protocol: TCP     
      port: 80
      targetPort: 8080
  type: ClusterIP
