apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appId }}-service
spec:
  selector:
    app: {{ .Values.appId }}-app 
  type: ClusterIP
  ports:
    - name: idp-https
      protocol: TCP      
      port: {{ .Values.port }}
      targetPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appId }}-metrics-service
spec:
  selector:
    app: {{ .Values.appId }}-app 
  type: ClusterIP
  ports:
    - name: idp-metrics
      protocol: TCP      
      port: 80
      targetPort: 8080
