apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appId }}-service
spec:
  selector:
    app: {{ .Values.appId }}-app 
  ports:
    - protocol: TCP 
      port: {{ .Values.port }}
      targetPort: 5001
  type: ClusterIP
