appId: webclient
port: 443
memory: "1024Mi"
cpu: "1024m"  
replicas: 1
idpUrl: "https://authminion-staging-testbed.assistdevtest.com"
GruUrl: "https://gru-staging-testbed.assistdevtest.com"
configmap:
  name: webclient-configmap-v1
image:
  name: 227368022383.dkr.ecr.ap-northeast-1.amazonaws.com/webclient
  tag: v240301_001

OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector-service.observability.svc.cluster.local:4317"
OTEL_EXPORTER_OTLP_PROTOCOL: "grpc"
OTEL_EXPORTER_OTLP_HEADERS:
