apiVersion: ako.vmware.com/v1alpha1
kind: AviInfraSetting
metadata:
  name: infrasetting
spec:
  network:
    enablePublicIP: true
---
apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  name: avi-ingress-class
spec:
  controller: ako.vmware.com/avi-lb
  parameters:
    apiGroup: ako.vmware.com
    kind: AviInfraSetting
    name: infrasetting