apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: jedi-staging-red
  region: ap-northeast-1
  version: "1.29"
 
vpc:
  id: vpc-024ffa78034e61c48
  subnets:
    private:
      ap-northeast-1a:
        id: subnet-0737f43649c3b6f6f
      ap-northeast-1c:
        id: subnet-0fe421bb0c0fb9c5a
    public:
      ap-northeast-1a:
        id: subnet-03f173e02121e48e4
      ap-northeast-1c:
        id: subnet-00953eba37504972d

iam:
  withOIDC: true
 
addons:
- name: aws-ebs-csi-driver
  version: v1.26.1-eksbuild.1
  attachPolicyARNs:
  - arn:aws:iam::aws:policy/service-role/AmazonEBSCSIDriverPolicy
 
managedNodeGroups:
  - name: managed-ng-jedi-staging-red
    instanceType: m7a.xlarge
    privateNetworking: true
    minSize: 3
    maxSize: 3
    desiredCapacity: 3
    volumeSize: 20
    ssh:
      allow: true