apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: signalr-assistdevtest-tls
  namespace: default
spec:
  secretName: signalr-assistdevtest-tls
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  dnsNames:
  - signalr-staging-red.assistdevtest.com
  - signalr-1-staging-red.assistdevtest.com
  - signalr-2-staging-red.assistdevtest.com
