apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-staging-classic
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io  
  labels:
    ENV: staging
spec:
  project: classic
  source:
    repoURL: 'https://prometheus-community.github.io/helm-charts'
    targetRevision: 25.8.0
    chart: prometheus
    helm:
      releaseName: dapr-prom
      values: |-
        extraScrapeConfigs: |
          - job_name: 'blackbox'
            metrics_path: /probe
            params:
              module: [http_2xx]  # Look for a HTTP 200 response.
            static_configs:
              - targets:
                - http://gru-dapr.default.svc:9090
                - http://macminion-dapr.default.svc:9090
            relabel_configs:
              - source_labels: [__address__]
                target_label: __param_target
              - source_labels: [__param_target]
                target_label: instance
              - target_label: __address__
                replacement: blackbox-prometheus-blackbox-exporter.observability.svc.cluster.local:9115
          - job_name: aggregated-trace-metrics
            static_configs:
              - targets:
                  - otel-collector-service.observability.svc.cluster.local:8889
          - job_name: services
            static_configs:
              - targets:
                  - gru-service.default.svc.cluster.local:80
                  - macminion-service.default.svc.cluster.local:80
                  - authminion-service.default.svc.cluster.local:80
                  - anchorservice-service.default.svc.cluster.local:80
                  - enrollmentservice-service.default.svc.cluster.local:80
                  - cadvisor.observability.svc.cluster.local:8080
                  - kube-state-metrics.observability.svc.cluster.local:8080                 
  destination:
    name: 'cloudgate@tmather@jedi-staging-classic.ap-northeast-1.eksctl.io'
    namespace: observability
  syncPolicy:
    syncOptions:
    - CreatNamespace=true
    automated:
      selfHeal: true
