apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tempo-staging-classic
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io/background 
  labels:
    ENV: staging
spec:
  project: classic
  source:
    repoURL: 'https://grafana.github.io/helm-charts'
    targetRevision: 1.7.1
    chart: tempo
    helm:
      releaseName: tempo
      values: |-
        replicas: 1
  destination:
    name: 'cloudgate@tmather@jedi-staging-classic.ap-northeast-1.eksctl.io'
    namespace: observability
  syncPolicy:
    syncOptions:
    - CreatNamespace=true
    automated:
      selfHeal: true
