apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: signalr-staging-idp
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io  
  labels:
    ENV: staging
spec:
  project: idp
  source:
    repoURL: 'ssh://git@stash.air-watch.com:7999/aplnt/argocd.git'
    path: k8s/staging/apps/signalr
    targetRevision: main
  destination:
    name: 'cloudgate@tmather@jedi-staging-idp.ap-northeast-1.eksctl.io'
    namespace: default
  syncPolicy:
    syncOptions:
    - CreatNamespace=true
    automated:
      selfHeal: true
