apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: jedi-staging-argocd
  region: ap-northeast-1
  version: "1.28"
 
vpc:
  id: vpc-024ffa78034e61c48
  subnets:
    private:
      ap-northeast-1a:
        id: subnet-04cb8b613f200ae0a
      ap-northeast-1c:
        id: subnet-07a45b7a519d58bcd
    public:
      ap-northeast-1a:
        id: subnet-01bdd2c6abbf8262a
      ap-northeast-1c:
        id: subnet-06c5e0ebbf8bd3205

iam:
  withOIDC: true
 
addons:
- name: aws-ebs-csi-driver
  version: v1.23.0-eksbuild.1
  attachPolicyARNs:
  - arn:aws:iam::aws:policy/service-role/AmazonEBSCSIDriverPolicy
 
managedNodeGroups:
  - name: managed-ng-jedi-staging-argocd
    instanceType: m6a.xlarge
    privateNetworking: true
    minSize: 5
    maxSize: 5
    desiredCapacity: 5
    volumeSize: 80
    ssh:
      allow: true