apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: jedi-staging-green
  region: ap-northeast-1
  version: "1.29"
 
vpc:
  id: vpc-024ffa78034e61c48
  subnets:
    private:
      ap-northeast-1a:
        id: subnet-0367ed7716766b347
      ap-northeast-1c:
        id: subnet-09794c05bf056df5a
    public:
      ap-northeast-1a:
        id: subnet-0ed7814501772d9d2
      ap-northeast-1c:
        id: subnet-04f49e233aecaf8ba

iam:
  withOIDC: true
 
addons:
- name: aws-ebs-csi-driver
  version: v1.26.1-eksbuild.1
  attachPolicyARNs:
  - arn:aws:iam::aws:policy/service-role/AmazonEBSCSIDriverPolicy
 
managedNodeGroups:
  - name: managed-ng-jedi-staging-green
    instanceType: m6a.xlarge
    privateNetworking: true
    minSize: 5
    maxSize: 5
    desiredCapacity: 5
    volumeSize: 80
    ssh:
      allow: true