apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cadvisor-staging-iris
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io/background 
  labels:
    ENV: staging
spec:
  project: iris
  source:
    repoURL: 'https://ckotzbauer.github.io/helm-charts'
    targetRevision: 2.3.1
    chart: cadvisor
    helm:
      releaseName: cadvisor
      values: |-
        replicas: 1
  destination:
    name: 'cloudgate@tmather@jedi-staging-iris.ap-northeast-1.eksctl.io'
    namespace: observability
  syncPolicy:
    syncOptions:
    - CreatNamespace=true
    automated:
      selfHeal: true
