apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: authminion-staging-purple
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io  
  labels:
    ENV: staging
spec:
  project: purple
  source:
    repoURL: 'https://github.com/tmather99/argocd.git'
    path: k8s/staging/apps/testbed/staging/purple/authminion
    targetRevision: main
  destination:
    name: 'cloudgate@tmather@jedi-staging-purple.ap-northeast-1.eksctl.io'
    namespace: default
  syncPolicy:
    syncOptions:
    - CreatNamespace=true
    automated:
      selfHeal: true
